#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

function init_deps {
  cd python
  virtualenv .venv
  set +o nounset
  source .venv/bin/activate
  set -o nounset
  pip install pytest hypothesis==1.19.0
}


function run_tests {
  PYTHONPATH=. py.test tests
}

init_deps
run_tests
