#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

set -o xtrace

: ${BUILD_TYPE:=Release}

function set_travis_compiler {
  if [[ -n "${CLANG_VERSION:-}" ]]; then
    export CC="clang-${CLANG_VERSION}" ;
    export CXX="clang++-${CLANG_VERSION}" ;
    export GCOV="llvm-cov-${CLANG_VERSION}" ;
  elif [[ -n "${GCC_VERSION:-}" ]]; then
    export CC="gcc-${GCC_VERSION}" ;
    export CXX="g++-${GCC_VERSION}" ;
    export GCOV="gcov-${GCC_VERSION}" ;
  fi
}

function run_tests {
  local name=$1

  local dir="build-${name}"

  # if you change this, modify `python/twiddle/c.py` accordingly.
  export BUILD_DIR=$dir

  mkdir -p "$dir"

  if [[ ${name:-} = "avx512" ]]; then
    CMAKE_FLAGS="-DUSE_AVX512=ON"
  elif [[ ${name:-} = "avx2" ]]; then
    CMAKE_FLAGS="-DUSE_AVX2=ON"
  elif [[ ${name:-} = "avx" ]]; then
    CMAKE_FLAGS="-DUSE_AVX=ON"
  else
    # valgrind seems to fail on avx instruction in travis
    CMAKE_FLAGS="-DUSE_VALGRIND=ON"
  fi

  pushd $dir

  cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
        ${CMAKE_FLAGS:-} ..

  # disable FORK (and incidently timeouts)
  export CK_FORK=no

  # unit tests
  make all test VERBOSE=1
  # property python tests
  popd

  pushd python
  run_property_tests
  popd

}

function run_property_tests {
  if [[ ${TRAVIS_PULL_REQUEST:-} != "false" ]]; then
    py_dir=.
    venv_dir=${py_dir}/.venv
    virtualenv ${venv_dir}
    set +o nounset
    source ${venv_dir}/bin/activate
    set -o nounset
    pip install pytest hypothesis==1.19.0
    PYTHONPATH=${py_dir} py.test tests
  fi
}


set_travis_compiler

run_tests portable
run_tests avx
