source "http://rubygems.org"

platforms :rbx do
    gem 'rubysl', '~> 2.0'
end

gem 'docurium', :git => 'https://github.com/fsaintjacques/docurium.git', :branch => 'feature/group-command'

# vim:ft=ruby
