#!/usr/bin/env bash
set -o nounset

FILE_EXTS=${FILE_EXTS:-(c|h)}

get_files() {
  git diff --cached --name-only --diff-filter=ACMRT | \
  egrep "\.$FILE_EXTS\$"
}

_IFS=$IFS
IFS='\n'
FILES=($(get_files))
IFS=$_IFS

for file in "${FILES[@]}"; do
  clang-format -output-replacements-xml "$file" | cmp -s "$file" -
  if [ $? -ne 0 ]; then
    echo "File does not respect formatting style: $file" 1>&2
    exit 1
  fi
done
